theme: jekyll-theme-leap-day
title: A/B Checklists
description: Three Key Checklists and Remedies for Trustworthy Analysis of Online Controlled Experiments at Scale
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
